/**
 * AUTHENTICATION REDUCER
 */
export const USER_LOGIN_TOGGLE = 'USER_LOGIN_TOGGLE';

/**
 * SIDE REDUCER
 */
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';

/**
 * MODAL LISTENER REDUCER
 */
export const OPEN_PRAYER_MODAL = 'OPEN_PRAYER_MODAL';
export const CLOSE_PRAYER_MODAL = 'CLOSE_PRAYER_MODAL';