/**
 * AUTHENTICATION REDUCER
 */
export const USER_LOGIN_TOGGLE = 'USER_LOGIN_TOGGLE';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const SET_IS_SUBSCRIBED_TO_PUSH_NOTIFICATION = 'SET_IS_SUBSCRIBED_TO_PUSH_NOTIFICATION';

/**
 * SIDE REDUCER
 */
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';

/**
 * MODAL LISTENER REDUCER
 */
export const OPEN_PRAYER_MODAL = 'OPEN_PRAYER_MODAL';
export const CLOSE_PRAYER_MODAL = 'CLOSE_PRAYER_MODAL';

/**
 * PRAYERS REDUCER
 */
export const PRAYERS_FETCHED = 'PRAYERS_FETCHED';
export const PRAYERS_ERROR = 'PRAYERS_ERROR';
export const PRAYERS_START_FETCHING = 'PRAYERS_START_FETCHING';
export const PRAYERS_STOP_REQUEST = 'PRAYERS_STOP_REQUEST';
export const PRAYER_UPDATE_REQUEST = 'PRAYER_UPDATE_REQUEST';
export const PRAYER_UPDATE_SUCCESS = 'PRAYER_UPDATE_SUCCESS';
export const PRAYER_UPDATE_ERROR = 'PRAYER_UPDATE_ERROR';
export const PRAYER_ADD_REQUEST = 'PRAYER_ADD_REQUEST';
export const PRAYER_ADD_SUCCESS = 'PRAYER_ADD_SUCCESS';
export const PRAYER_RESET = 'PRAYER_RESET';
export const PRAYER_ADD_ERROR = 'PRAYER_ADD_ERROR';

export const PRAYER_START_FETCHING = 'PRAYER_START_FETCHING';
export const PRAYER_ERROR = 'PRAYER_ERROR';
export const PRAYER_FETCHED = 'PRAYER_FETCHED';

/**
 * COLLECTIONS REDUCER
 */
export const COLLECTIONS_FETCHED = 'COLLECTIONS_FETCHED';
export const COLLECTIONS_ERROR = 'COLLECTIONS_ERROR';
export const COLLECTIONS_START_FETCHING = 'COLLECTIONS_START_FETCHING';
export const COLLECTIONS_STOP_REQUEST = 'COLLECTIONS_STOP_REQUEST';
export const COLLECTION_UPDATE_REQUEST = 'COLLECTION_UPDATE_REQUEST';
export const COLLECTION_UPDATE_SUCCESS = 'COLLECTION_UPDATE_SUCCESS';
export const COLLECTION_UPDATE_ERROR = 'COLLECTION_UPDATE_ERROR';
export const COLLECTION_ADD_REQUEST = 'COLLECTION_ADD_REQUEST';
export const COLLECTION_ADD_SUCCESS = 'COLLECTION_ADD_SUCCESS';
export const COLLECTION_ADD_ERROR = 'COLLECTION_ADD_ERROR';
export const COLLECTION_FETCHING = 'COLLECTION_FETCHING';
export const COLLECTION_FETCHED = 'COLLECTION_FETCHED';

/**
 * ALERT REDUCER
 */
export const OPEN_ALERT = 'OPEN_ALERT';
export const CLOSE_ALERT = 'CLOSE_ALERT';

/**
 * FEED REDUCER
 */
export const FEED_FETCHED = 'FEED_FETCHED';
export const QUOTE_UPDATED = 'QUOTE_UPDATED';
export const FEED_ERROR = 'FEED_ERROR';
export const FEED_START_FETCHING = 'FEED_START_FETCHING';
export const QUOTE_START_UPDATING = 'QUOTE_START_UPDATING';
export const FEED_RESET_ERROR = 'FEED_RESET_ERROR';
export const FEED_STOP_REQUEST = 'FEED_STOP_REQUEST';