/**
 * AUTHENTICATION REDUCER
 */
export const USER_LOGIN_TOGGLE = 'USER_LOGIN_TOGGLE';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

/**
 * SIDE REDUCER
 */
export const TOGGLE_SIDE_BAR = 'TOGGLE_SIDE_BAR';

/**
 * MODAL LISTENER REDUCER
 */
export const OPEN_PRAYER_MODAL = 'OPEN_PRAYER_MODAL';
export const CLOSE_PRAYER_MODAL = 'CLOSE_PRAYER_MODAL';

/**
 * PRAYERS REDUCER
 */
export const PRAYERS_FETCHED = 'PRAYERS_FETCHED';
export const PRAYERS_ERROR = 'PRAYERS_ERROR';
export const PRAYERS_START_FETCHING = 'PRAYERS_START_FETCHING';
export const PRAYERS_STOP_REQUEST = 'PRAYERS_STOP_REQUEST';
export const PRAYER_UPDATE_REQUEST = 'PRAYER_UPDATE_REQUEST';
export const PRAYER_UPDATE_SUCCESS = 'PRAYER_UPDATE_SUCCESS';
export const PRAYER_UPDATE_ERROR = 'PRAYER_UPDATE_ERROR';
export const PRAYER_ADD_REQUEST = 'PRAYER_ADD_REQUEST';
export const PRAYER_ADD_SUCCESS = 'PRAYER_ADD_SUCCESS';
export const PRAYER_ADD_ERROR = 'PRAYER_ADD_ERROR';